version: '3'

services:
  # Postgres Server
  postgres-server:
    image: postgres:17.4-alpine3.21
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_apex
  # Apex Mono Api
  apex-server:
    build:
      context: .
    command: npm run start:dev
    ports:
      - '4000:3000'
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - postgres-server
    environment:
      SECRET_KEY: d5b78faed7f61e7d
      DB_HOST: postgres-server
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASS: db_password
      DB_NAME: db_apex
  # Storage Server
  storage-server:
    image: registry.digitalocean.com/softmora/utils/storage-ms:5385118
    ports:
      - '4100:3000'
    environment:
      IAM_ACCESS_KEY: ${IAM_ACCESS_KEY}
      IAM_SECRET_KEY: ${IAM_SECRET_KEY}
      AWS_REGION: us-east-1
      BUCKET_NAME: huitzilin