export { Classroom } from './classroom/entities/classroom.entity';
export { Course } from './course/entities/course.entity';
export { Cycle } from './cycle/entities/cycle.entity';
export { Debit } from './debit/entities/debit.entity';
export { Enrollment } from './enrollment/entities/enrollment.entity';
export { Fee } from './fee/entities/fee.entity';
export { Student } from './student/entities/student.entity';
export { Teacher } from './teacher/entities/teacher.entity';
export { Tutor } from './tutor/entities/tutor.entity';
